# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-17 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180418_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='student',
            new_name='students',
        ),
    ]
