# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-18 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180418_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
    ]
